# Generated by Django 4.2.2 on 2023-06-20 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("club_name", models.CharField(max_length=100)),
                ("contact", models.EmailField(max_length=254)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="President",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("grade", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("room_number", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("agenda", models.CharField(max_length=50)),
                ("date_and_time", models.DateTimeField()),
                ("location", models.CharField(max_length=50)),
                ("open_to", models.CharField(max_length=50)),
                ("sign_up", models.TextField()),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shark_club_org.club",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="club",
            name="president",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shark_club_org.president",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="sponsor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shark_club_org.sponsor"
            ),
        ),
    ]
